version: '3'
services:
    api:
        build: ./
        environment:
            - loglevel=none
            - NODE_ENV=development
            - MONGODB_URI=mongodb://mongodb:27017/mongo
            - PORT=3000
            - API_SECRET=<api_key_goes_here>
            - APPLICATION_NAME=NodeApi
            - APPLICATION_URL=http://localhost:3001/ 
            - SMTP_EMAIL=
            - SMTP_SENDER=
            - SMTP_PASSWORD=
            - SMTP_SERVICE=gmail
        volumes:
            - ./:/usr/src/app 
        working_dir: /usr/src/app
        command: bash -c "npm install &&  npm run start-docker"
        ports:
            - 3000:3000 
        depends_on:
            - mongodb 
    mongodb:
        image: mongo
        ports:
            - 27017:27017